apiVersion: v1
kind: ConfigMap
metadata:
  name: campusconnect-config
  namespace: lab8
  labels:
    app.kubernetes.io/part-of: campusconnect
data:
  PORT_GATEWAY: "3000"
  PORT_USER: "3001"
  PORT_PRODUCT: "3002"
  PORT_ORDER: "3003"
  USER_SERVICE_URL: "http://user-service:3001"
  PRODUCT_SERVICE_URL: "http://product-service:3002"
  ORDER_SERVICE_URL: "http://order-service:3003"
  CORS_ORIGIN: "*"
