apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: lab8
  labels:
    app: api-gateway
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: campusconnect
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
